openapi: "3.0.2"
info:
  title: ReaGo
  version: "1.0"
servers:
  - url: http://localhost:8080

paths:
  /api/data:
    get:
      description: "Get data"
      parameters: []
      responses:
        "200":
          description: "Successfully get data"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The message string.
  /albums:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: OK
